"repnyek@google.com",
"carlsonalex@google.com",
"soboyle@google.com",
"purnimay@google.com",
"chongy@zettastone.com",
"wangxj@zettastone.com",
"jack.xu@zettastone.com",
"raj@awaveip.com",
"derek.stephenson@awaveip.com",	
"tom.tsopelas@awaveip.com",
"kenny.tung@awaveip.com",
"alex.mann@awaveip.com ",
"Sachin.Goel@aquantia.com",
"Michael.Smith@aquantia.com",
"Saravanan.Shanmugavelu@aquantia.com",
"Satyajit.Chowdhury@aquantia.com",
"Seema.Shetty@aquantia.com",
"Ted.Eaton@aquantia.com",
"pbalakrishnan@violinsystems.com",
"mgreenberg@violinsystems.com",
"vkrishnamurt@micron.com",
"shazra@micron.com",
"pbordoloi@micron.com",
"ashtepel@micron.com",
"mikeou@micron.com",
"labraham@micron.com",
"jenny.c.kardos@boeing.com",
"kyle.m.upton@boeing.com",
"edchun@fb.com",
"Chris.Tann@Oculus.com",
"Vinay.Prabhu@Oculus.com",
"Omid.Taheri@idt.com",
"Takehito.Sasaki@idt.com",
"toby.schaffer@idt.com",
"Kevin.Sheng@idt.com",
"dave.brown@idt.com ",
"Rolf.Huelss@idt.com ",
"Vasil.Angelov@idt.com",
"siddartha.kavilipati@mobaitech-inc.com",
"victor.szeto@mobaitech-inc.com",
"rupesh.parab@mobaitech-inc.com ",
"sam.xu@netint.ca",
"yue.li@netint.ca ",
"peter.wu@netint.ca",
"zhuo.fu@idexbiometric",
"tom.tsopelas@awaveip.com",
"kenny.tung@awaveip.com",
"deeppat@amazon.com",
"michael.kang@dji.com",
"hayden.chen@dji.com",
"david.guo@dji.com",
"mary.downes@decawave.com",
"mohammed.elbadri@coveloz.com",
"joseph.botros@coveloz.com ",
"alexander.apel@rockwellcollins.com",
"lisa.frey@rockwellcollins.com",
"mohsenn@icron.com",
"remcos@icron.com",
"Roy.Hopgood@mrcy.com",
"skerzner@mrcy.com",
"davidf@icron.com ",
"brian.davis@yellowbrick.io ",
"lisa.wrightson@yellowbrick.io ",
"baranidharan.sivapatham@barclays.com ",
"mounika.x.garlapati@barclays.com ",
"MPETTIGR@harris.com",
"Dillip.Dash@wdc.com ",
"Maulik.Patel@wdc.com ",
"Mike.Lemus@sandisk.com ",
"Jian.Niu@sandisk.com ",
"Dillip.Dash@wdc.com ",
"Maulik.Patel@wdc.com ",
"Mike.Lemus@sandisk.com ",
"Jian.Niu@sandisk.com ",
"griffinjamesa@johndeere.com ",
"JMcClay@ALLEGROMICRO.com",
"kdemanche@ALLEGROMICRO.com",
"rmacomber@ALLEGROMICRO.com ",
"Silvan.Forrer@leica-geosystems.com",
"jgoeller@intrinsix.com",
"Dana.Caspi@arm.com",
"Jacob.Ludwig@bsci.com",
"Jacob.Ludwig@bsci.com",
"marco.deleon@rockwellcollins.com",
"Bryan.Jefferson@rockwellcollins.com",
"Brandon.Whitney@rockwellcollins.com ",
"jenny.c.kardos@boeing.com",
"kyle.m.upton@boeing.com",
"lawrence.y.ching@boeing.com",
"kurt.k.sato@boeing.com ",
"Dana.Caspi@arm.com",
"Hanan.Khanger@arm.com",
"Dedi.Yellin@arm.com ",
"gillersa@amazon.com	",
"freunde@amazon.com	",
"deeppat@amazon.com "