"derek.stephenson@awaveip.com",	
"kenny.tung@awaveip.com",
"alex.mann@awaveip.com ",
"zhuo.fu@idexbiometric",
"hayden.chen@dji.com",
"joseph.botros@coveloz.com ",
"baranidharan.sivapatham@barclays.com ",
"mounika.x.garlapati@barclays.com ",
"kurt.k.sato@boeing.com ",
"gillersa@amazon.com	",
"freunde@amazon.com	",
