/*  

 *** This file is auto generated by IDesignSpec (http://www.agnisys.com) . Please do not edit this file. ***
created by          : 
generated by        : charles.rainey
IDesignSpec ver     :  7.6.12.0 

**** This code is generated with the following settings ***
Reg Width                  : 32
Address Unit               : 8
C++ Types int              : hwint
Bus Type                   : AMBA3AHBLITE
BigEndian                  : true
LittleEndian               : true
Dist. Decode and Readback  : false
------------------------------------------------------------ */ 







`define ROT_SYS_REGS_ADDR 'h0
`define ROT_SYS_REGS_SIZE 'h4
`define ROT_SYS_REGS_MAA_CFG_ADDR `ROT_SYS_REGS_ADDR + 'h0
`define ROT_SYS_REGS_MAA_CFG_DEFAULT 'h00000000
`define ROT_SYS_REGS_MAA_CFG_EXP_TYPE_MSB 5
`define ROT_SYS_REGS_MAA_CFG_EXP_TYPE_LSB 4
`define ROT_SYS_REGS_MAA_CFG_EXP_TYPE_DEFAULT 'b00
`define ROT_SYS_REGS_MAA_CFG_OPD_SIZE_MSB 11
`define ROT_SYS_REGS_MAA_CFG_OPD_SIZE_LSB 8
`define ROT_SYS_REGS_MAA_CFG_OPD_SIZE_DEFAULT 'b0000












package ROT_SYS_regs_header_pkg;

typedef enum logic [3:0] {
  MAA_EXP_TYPE_e_PUB = 1,
  MAA_EXP_TYPE_e_PRV = 2
} MAA_EXP_TYPE_e;


typedef enum logic [15:0] {
  MAA_OPD_SIZE_e_OPD_2048 = 1,
  MAA_OPD_SIZE_e_OPD_3072 = 2,
  MAA_OPD_SIZE_e_OPD_4096 = 4,
  MAA_OPD_SIZE_e_OPD_RSVD = 8
} MAA_OPD_SIZE_e;


/*-------------------------------------------
Reg: ROT_SYS_REGS/MAA_CFG
 
-------------------------------------------*/
typedef struct packed {
   logic [31:12] padding_31;
   logic [11:8] OPD_SIZE;
   logic [7:6] padding_7;
   logic [5:4] EXP_TYPE;
   logic [3:0] padding_3;
} ROT_SYS_regs_MAA_CFG;

typedef struct packed {
   ROT_SYS_regs_MAA_CFG MAA_CFG;
} ROT_SYS_regs;

endpackage










